name: Set up node using nvm
description: Sets up a specific node.js version using nvm
author: irby
inputs:
  node-version:
    description: The node.js version to use according to nvm. Uses the version specified in .nvmrc if omitted.
    default: ""
  node-mirror:
    description: The node.js mirror to use
    default: https://nodejs.org/dist/
branding:
  icon: download
  color: green
runs:
  using: node20
  main: index.js
