name: NVM Setup Node
description: Sets up a specific node version using nvm
author: irby
inputs:
  node-version:
    description: Install specific version of Node using NVM. If omitted, it will use the .nvmrc value at your project root (if available) or fall back to the value in .nvmrc for this action.
    default: ""
  node-mirror:
    description: The node.js mirror to use
    default: https://nodejs.org/dist/
branding:
  icon: download
  color: green
runs:
  using: node20
  main: index.js
